[project]
name = "tinylab"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "tinygrad",
]

[tool.uv.sources]
tinygrad = { path = "../../tinygrad" }
